// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jruwyxlhbeytcggykfoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpydXd5eGxoYmV5dGNnZ3lrZm96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjEzMDMsImV4cCI6MjA2OTM5NzMwM30.zgaFmT4DAXEjIpWgK3jOuAXGDK8pxyKRGtGWc3yOZEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});